import type { Theme } from "../core/types.js";

/** Expressive showcase theme with aurora-inspired accents and balanced contrast. */
export const yuirinxAurora: Theme = {
  id: "yuirinx-aurora",
  name: "Yuirinx Aurora",
  type: "dark",
  foreground: "#e5e8f4",
  background: "#0d0b18",
  selection: "#32284f",
  lineHighlight: "#151126",
  fallbackPalette: [
    "#67dcff",
    "#c99cff",
    "#7ee0b8",
    "#ffbd70",
    "#ff78ae",
    "#9bbcff",
  ],
  tokens: {
    comment: { color: "#756f91", fontStyle: "italic" },
    keyword: { color: "#ff78ae", fontWeight: "semibold" },
    operator: { color: "#a9a1c2" },
    punctuation: { color: "#8983a0" },
    string: { color: "#7ee0b8" },
    "string.escape": { color: "#ffd479", fontWeight: "semibold" },
    "string.interpolation": { color: "#e69cff" },
    number: { color: "#ffbd70" },
    boolean: { color: "#ffbd70", fontWeight: "semibold" },
    null: { color: "#ffbd70", fontStyle: "italic" },
    regex: { color: "#64ddd0" },
    function: { color: "#67dcff" },
    variable: { color: "#e5e8f4" },
    property: { color: "#9bbcff" },
    constant: { color: "#ffd479" },
    type: { color: "#c99cff" },
    class: { color: "#c99cff", fontWeight: "semibold" },
    namespace: { color: "#b596e8" },
    builtin: { color: "#83c9ff" },
    tag: { color: "#ff78ae" },
    attribute: { color: "#ffbd70" },
    "attribute.value": { color: "#7ee0b8" },
    selector: { color: "#ff8bb7" },
    "property.css": { color: "#83c9ff" },
    value: { color: "#64ddd0" },
    unit: { color: "#d8a3ff" },
    "at-rule": { color: "#e69cff" },
    heading: { color: "#67dcff", fontWeight: "bold" },
    emphasis: { color: "#c99cff", fontStyle: "italic" },
    strong: { color: "#ffd479", fontWeight: "bold" },
    link: { color: "#83c9ff", textDecoration: "underline" },
    url: { color: "#64ddd0" },
    code: { color: "#7ee0b8" },
    quote: { color: "#a9a1c2", fontStyle: "italic" },
    list: { color: "#ffbd70" },
    inserted: { color: "#7ee0b8" },
    deleted: { color: "#ff78ae" },
    important: { color: "#ff9f6b", fontWeight: "bold" },
    meta: { color: "#8983a0" },
    decorator: { color: "#e69cff" },
    annotation: { color: "#e69cff" },
    label: { color: "#67dcff" },
  },
};
