import type { Theme } from "../core/types.js";

/** Premium dark theme inspired by ink, glass, and restrained editor contrast. */
export const yuirinxNoir: Theme = {
  id: "yuirinx-noir",
  name: "Yuirinx Noir",
  type: "dark",
  foreground: "#d7deea",
  background: "#0a0d14",
  selection: "#24314b",
  lineHighlight: "#111722",
  fallbackPalette: [
    "#73d7e7",
    "#c5a5f5",
    "#9fd5a9",
    "#e8bd72",
    "#f07f9f",
    "#a8c7fa",
  ],
  tokens: {
    comment: { color: "#667085", fontStyle: "italic" },
    keyword: { color: "#f07f9f", fontWeight: "semibold" },
    operator: { color: "#9ba8bd" },
    punctuation: { color: "#7f8ba0" },
    string: { color: "#9fd5a9" },
    "string.escape": { color: "#f2c879", fontWeight: "semibold" },
    "string.interpolation": { color: "#e4a6ff" },
    number: { color: "#e8bd72" },
    boolean: { color: "#e8bd72", fontWeight: "semibold" },
    null: { color: "#e8bd72", fontStyle: "italic" },
    regex: { color: "#a8d8d1" },
    function: { color: "#73d7e7" },
    variable: { color: "#d7deea" },
    property: { color: "#a8c7fa" },
    constant: { color: "#f1ca86" },
    type: { color: "#c5a5f5" },
    class: { color: "#c5a5f5", fontWeight: "semibold" },
    namespace: { color: "#a78bda" },
    builtin: { color: "#8fc8ff" },
    tag: { color: "#f07f9f" },
    attribute: { color: "#e8bd72" },
    "attribute.value": { color: "#9fd5a9" },
    selector: { color: "#f29bb2" },
    "property.css": { color: "#8fc8ff" },
    value: { color: "#a8d8d1" },
    unit: { color: "#d5a4f5" },
    "at-rule": { color: "#e4a6ff" },
    heading: { color: "#73d7e7", fontWeight: "bold" },
    emphasis: { color: "#c5a5f5", fontStyle: "italic" },
    strong: { color: "#f1ca86", fontWeight: "bold" },
    link: { color: "#8fc8ff", textDecoration: "underline" },
    url: { color: "#7fc8b2" },
    code: { color: "#9fd5a9" },
    quote: { color: "#9ba8bd", fontStyle: "italic" },
    list: { color: "#e8bd72" },
    inserted: { color: "#9fd5a9" },
    deleted: { color: "#f07f9f" },
    important: { color: "#ffb86b", fontWeight: "bold" },
    meta: { color: "#7f8ba0" },
    decorator: { color: "#e4a6ff" },
    annotation: { color: "#e4a6ff" },
    label: { color: "#73d7e7" },
  },
};
